---
layout: post
categories: [Python]
description: none
keywords: Python
---
# Python异常处理
Python具备完整而强大的异常处理能力。初学者也许不认同这个说法，因为他们在使用Python的过程中可能经常会遇到解释器弹出一大堆提示信息后程序被迫终止的情况，但这恰恰是Python异常处理能力强大的一种体现。如果程序终止却没有给出任何提示信息，那才是真正的麻烦。

Python的内置类Exception预定义了18类、50余种错误和警告类型，其中语法错误（SyntaxError）、模块导入错误（ImportError）、类型错误（TypeError）、索引错误（IndexError）、键错误（KeyError）、缩进错误（IndentationError）等都是最常见的错误类型。

若程序在运行过程中发生了Exception预定义的错误，程序的执行过程就会发生改变，抛出Exception异常对象，进入异常处理。如果Exception异常对象没有被捕获，程序就会执行回溯（Traceback）来终止程序。除了程序运行抛出异常，还可以使用raise关键字来触发异常。

```shell
>>> def try_error(n=0):
        try:
            if n == 0:
                raise Warning('这是警告信息')
            if n == 1:
                raise SyntaxError('这是语法错误')
            if n == 2:
                raise IndentationError('这是缩进错误')
            if n == 3:
                raise FileNotFoundError('请求不存在的文件或目录')
        except Warning as e:
            print(e)
        except (SyntaxError, IndentationError) as e:
            print(e)
        except FileNotFoundError as e:
            print(e)
        finally:
            print('善后工作')

>>> try_error()
这是警告信息
善后工作
>>> try_error(1)
这是语法错误
善后工作
>>> try_error(2)
这是缩进错误
善后工作
>>> try_error(3)
请求不存在的文件或目录
善后工作
```
上面的例子使用raise关键字模拟代码中可能出现的常见错误和警告，捕获并分类处理不同的错误和警告异常，最后不管是否捕获到异常都会执行finally语句。实际应用时，一个异常捕获与处理的代码结构中，finally语句是可选的，except语句至少有一个。except语句也可以不指定任何异常类型，或指定Excpetion类。所有的常规异常和警告都是由Excpetion类派生的。












